use mavenmovies;
-- Q1 Retrieve the total numbers of rentals made in the sakila database;

SELECT count(*) FROM rental;                                                 -- ANS = 16044

-- Q2 Find the average rental duration (in days) of movies rented from the Sakila database

SELECT AVG(rental_duration) AS avg_dur FROM film;                            -- ANS = 4.9850

-- Q3 Display the first name and last name of customers in upper case

SELECT upper(concat(first_name," ", last_name)) AS full_name FROM customer;

-- Q4 Extract the month from the rental date and display it alongside the rental ID

SELECT month(rental_date) Rental_month, rental_id FROM rental;

-- Q5 Retrieve the count of rentals for each customer (display customer ID and the count of rentals)

SELECT customer_id, count(*) AS tot_rental FROM rental
GROUP BY customer_id;

-- Q6 Find the total revenue generated by each store

SELECT store_id, sum(amount) as tot_revenue FROM store
JOIN payment ON store.manager_staff_id=payment.staff_id
GROUP BY store_id;

-- Q7 Display the title of the movie, customer's first name and last name who rented it

SELECT * FROM film;
SELECT * FROM rental;
SELECT * FROM inventory;
SELECT * FROM customer;

SELECT title, first_name, last_name FROM inventory
JOIN film ON inventory.film_id=film.film_id
JOIN rental ON inventory.inventory_id=rental.inventory_id
JOIN customer ON rental.customer_id=customer.customer_id
WHERE rental.rental_id IS NOT NULL;

-- Q8 Retrieve the names of all actors who have appeared in the film "Gone with the Wind".
SELECT * FROM actor;
SELECT * FROM film_actor;
SELECT * FROM film;











